# File: skaffold.yaml
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: gen-erics-pacs

build:
  # Tell Skaffold how to build images locally (using Docker/Rancher Desktop)
  local:
    push: false           # Don't push images for local clusters like k3d (Skaffold loads them directly)
    useBuildkit: true     # Use Docker BuildKit for potentially faster builds
    concurrency: 0        # Build all artifacts in parallel (0 means unlimited)
    # Below option avoids loop by only running 'go mod tidy' when explicitly triggered
    tryImportMissing: false # Don't try to import images from local Docker daemon
  
  # Define the container images Skaffold should build
  artifacts:
    # --- Backend Image ---
    - image: gen-erics-backend-skaffold 
      context: backend                  
      docker:
        dockerfile: Dockerfile          
      # Remove the automatic go mod tidy hook that was causing the infinite loop
      # Instead, run these commands manually before starting skaffold when needed
      # hooks:
      #   before:
      #     - command: ['sh', '-c', 'cd backend && go mod tidy && go mod vendor']
      # Define files to watch for this artifact
      sync:
        manual:
          - src: 'internal/**/*.go'
            dest: .

    # --- Frontend Image ---
    - image: gen-erics-frontend-skaffold
      context: frontend                
      docker:
        dockerfile: Dockerfile         
      # Add file sync for faster development
      sync:
        manual:
          - src: 'index.html'
            dest: /usr/share/nginx/html
          - src: 'style.css'
            dest: /usr/share/nginx/html
          - src: 'main.js'
            dest: /usr/share/nginx/html

deploy:
  helm:
    releases:
      - name: dev                    
        chartPath: infrastructure/helm/gen-erics
        namespace: default          
        valuesFiles:
          - infrastructure/gen-erics-values.yaml
        setValueTemplates:
          backend.image.repository: "{{.IMAGE_REPO_gen_erics_backend_skaffold}}"
          backend.image.tag: "{{.IMAGE_TAG_gen_erics_backend_skaffold}}"
          frontend.image.repository: "{{.IMAGE_REPO_gen_erics_frontend_skaffold}}"
          frontend.image.tag: "{{.IMAGE_TAG_gen_erics_frontend_skaffold}}"
        skipBuildDependencies: false
        wait: true

# Set up port-forwarding for easier development
# portForward:
# - resourceType: service
#   resourceName: dev-gen-erics-frontend
#   namespace: default
#   port: 80
#   localPort: 9000 # Access frontend via localhost:9000
# - resourceType: service
#   resourceName: dev-gen-erics-backend
#   namespace: default
#   port: 80
#   localPort: 8080 # Access backend API via localhost:8080
# - resourceType: service
#   resourceName: dev-postgresql
#   namespace: default
#   port: 5432
#   localPort: 5433 # Access postgres via localhost:5433

# Add cleanup profile to help with disk space
profiles:
  - name: cleanup
    patches:
      - op: add
        path: /build/local/cleanup
        value: true  # Enable cleanup of images when using this profile