# infrastructure/helm/gen-erics/templates/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gen-erics.fullname" . }}-backend
  labels:
    {{- include "gen-erics.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.backend.service.port | default 80 }}
      targetPort: {{ .Values.backend.containerPort | default 8000}}
      protocol: TCP
      name: http
  selector:
    {{- include "gen-erics.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend